app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$uploadFile(file1 = "iris.csv")
app$setInputs(submit = "click")
app$setInputs(req1 = "corrmat")
app$setInputs(selvar = c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"))
app$setInputs(submit2 = "click")
app$setInputs(req1 = "scatplot")
app$setInputs(submit1 = "click")
app$setInputs(req1 = "corrplot")
app$setInputs(selvar = c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"))
app$setInputs(submit3 = "click")
